const SELECT_LIST = {
  en: 'English',
  fr: 'French',
  es: 'Spanish',
  ar: 'Arabic',
  cmn: 'Mandarin',
  ru: 'Russian',
  pt: 'Portuguese',
  de: 'German',
  ja: 'Japanese',
  hi: 'Hindi',
  ms: 'Malay',
  fa: 'Persian',
  sw: 'Swahili',
  ta: 'Tamil',
  it: 'Italian',
  nl: 'Dutch',
  bn: 'Bengali',
  tr: 'Turkish',
  vi: 'Vietnamese',
  pl: 'Polish',
  jv: 'Javanese',
  pa: 'Punjabi',
  th: 'Thai',
  ko: 'Korean',
};
export default Object.entries(SELECT_LIST).map(([key, value]) => ({
  value: key,
  label: value,
}));
